name: "Setup Dependencies"
description: "Download and Install Dependencies"
runs:
    using: "composite"
    steps:
        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version-file: .nvmrc

        - uses: pnpm/action-setup@v2
          name: Install pnpm
          id: pnpm-install
          with:
            version: 7.15
            run_install: false

        - name: Get pnpm store directory
          id: pnpm-cache
          shell: bash
          run: |
            echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

        - uses: actions/cache@v3
          name: Setup pnpm cache
          with:
            path: ${{ steps.pnpm-cache.outputs.PNPM_STORE_PATH }}
            key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
            restore-keys: |
              ${{ runner.os }}-pnpm-store-

        - name: Install React Dependencies
          shell: bash
          run: pnpm install
