name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Dependencies
        uses: ./.github/actions/dependencies

      - name: Build
        shell: bash
        run: pnpm run build
