name: Lint

on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Dependencies
        uses: ./.github/actions/dependencies

      - name: Run linting
        run: ./tools/lint.sh
